DROP DATABASE IF EXISTS KICZAN_PRODUCTION_SYSTEM;
CREATE DATABASE KICZAN_PRODUCTION_SYSTEM;
USE KICZAN_PRODUCTION_SYSTEM;

-- Create the customers table
CREATE TABLE CUSTOMERS 
(
    	CUSTOMER_ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
    	CUSTOMER_NAME VARCHAR(48) NOT NULL,
);

-- Create the jobs table
CREATE TABLE JOBS
( 	
	JOB_ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	JOB_DESC TEXT NOT NULL,
);

-- Create the users table
CREATE TABLE USERS
(
	USER_ID	INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	USER_NAME VARCHAR(48) NOT NULL UNIQUE,
	CREATED_AT DATE NOT NULL,
	IS_ACTIVE BIT NOT NULL									
);

-- Create the roles table
CREATE TABLE ROLES 
(
   	ROLES_ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
    	ROLE_NAME VARCHAR(48) NOT NULL UNIQUE
);

-- Create the user roles table 
CREATE TABLE USER_ROLES
(
   	USER_ID INT NOT NULL,
    	ROLE_ID INT NOT NULL,
    	PRIMARY KEY (USER_ID, ROLE_ID),
   	CONSTRAINT fk_user_roles_user
        	FOREIGN KEY (USER_ID)
        	REFERENCES USERS (USER_ID)
        	ON DELETE CASCADE
        	ON UPDATE CASCADE,
    	CONSTRAINT fk_user_roles_role
        	FOREIGN KEY (ROLE_ID)
        	REFERENCES ROLES (ROLES_ID)
        	ON DELETE NO ACTION
        	ON UPDATE CASCADE
);

-- Create the audit log table
CREATE TABLE AUDIT_LOG 
(
    AUDIT_LOG_ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
    USER_ID INT NOT NULL,                 
    ENTITY VARCHAR(48) NOT NULL,
    ACTION VARCHAR(48) NOT NULL,
    OCCURRED_AT DATETIME2 NOT NULL DEFAULT GETDATE(),        
    CONSTRAINT fk_auditlog_user
        	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
       	 	ON UPDATE CASCADE
        	ON DELETE NO ACTION
); 

-- Create the operators table
CREATE TABLE OPERATORS
( 	
	OPERATOR_ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	JOB_ID INT NOT NULL,
	OPERATOR_NAME VARCHAR(48) NOT NULL,
    	CONSTRAINT FK_OPERATORS_JOBS
	FOREIGN KEY (JOB_ID)  REFERENCES jobs(JOB_ID)									
);
	
-- Create the part history table
CREATE TABLE PART_HISTORY
(
	PART_HISTORY_ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CUSTOMER_ID	INT	NOT NULL,
	OPERATOR_ID	INT	NOT NULL,
	PART_NUMBER	VARCHAR(128) NOT NULL,
	DATE_DUE DATE NOT NULL,
	PURCHASE_ORDER_NUMBER VARCHAR(128) NOT NULL,
	QTY	INT NOT NULL,
	OPERATIONS VARCHAR(128) NOT NULL,
	DATE_RECEIVED DATE NOT NULL,
	TO_DELETE BIT DEFAULT 0 NOT NULL,
    	CONSTRAINT FK_PART_HISTORY_CUSTOMERS
		FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    	CONSTRAINT FK_PART_HISTORY_OPERATORS
		FOREIGN KEY (OPERATOR_ID) REFERENCES OPERATORS(OPERATOR_ID)
);